kind: PersistentVolume
apiVersion: v1
metadata:
  name: k8s-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-03c4b4242d23db72a 
    fsType: ext4
