apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  nfs:
    server: fs-c23cd3fb.efs.ap-southeast-2.amazonaws.com 
    path: "/"
