apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-app
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: k8s-app
    spec:
      containers:
      - name: k8s-app
        image: 230367374156.dkr.ecr.ap-southeast-2.amazonaws.com/ecr-k8s-app:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: efs-pvc
          mountPath: "/App/Data"
      volumes:
      - name: efs-pvc
        persistentVolumeClaim:
          claimName: efs-pvc
